<?php

/**
 * @file
 * Allows to attach page_load_progress assets to all pages.
 */

/**
 * Implements hook_page_attachments().
 */
function page_load_progress_page_attachments(array &$attachments) {
  if (\Drupal::currentUser()->hasPermission('use page load progress') &&
      !strpos(\Drupal::service('path.current')->getPath(), 'admin/structure/views/')) {

    // Unconditionally attach assets to the page.
    $attachments['#attached']['library'][] = 'page_load_progress/page_load_progress';

    // Load module configs.
    $config = \Drupal::config('page_load_progress.settings');

    // Attach config settings.
    $attachments['#attached']['drupalSettings']['page_load_progress'] = [
      'delay' => $config->get('page_load_progress_time'),
      'elements' => $config->get('page_load_progress_elements'),
      'esc_key' => $config->get('page_load_progress_esc_key'),
    ];
  }
}
